# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 3
    labels:
      - "gradle"
      - "dependency-update"
    
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    commit-message:
      prefix: "docker"
    open-pull-requests-limit: 3
    labels:
      - "docker"
      - "dependency-update"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    commit-message:
      prefix: "actions"
    open-pull-requests-limit: 2
    labels:
      - "github-actions"
      - "ci-update"
      


