name: CI for FactoryX EDC
run-name: ${{ github.actor }} is testing out backend build

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Label Dependabot PR
        if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'factory-x-contributions/embedded-connector'
        run: gh pr edit "${{ github.event.pull_request.html_url }}" --add-label "dependency-update"

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build backend with Gradle Wrapper
        working-directory: ./backend
        run: ./gradlew build
        
      - name: Run Backend Tests
        working-directory: ./backend
        run: ./gradlew test

      - name: Generate Dependency Report
        working-directory: ./backend
        run: ./gradlew dependencies > dependency-report.txt

      # Upload Dependency Report
      - name: Upload Dependency Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-report
          path: ./backend/dependency-report.txt 

